services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - proxy
    restart: unless-stopped

  app:
    image: ghcr.io/prgrms-be-devcourse/nbe8-10-2-team02:latest
    container_name: back-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/back
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID}
      IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    networks:
      - proxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M

networks:
  proxy:
    name: proxy
    driver: bridge
