spring:
  datasource:
    url: jdbc:tc:pgvector:pg16:///test_db
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

custom:
  jwt:
    secretKey: "test-secret-key-32bytes-minimum-xxxxxxxxxxxx"
  accessToken:
    expirationSeconds: 300

igdb:
  base-url: "https://api.igdb.com/v4"
  client-id: "dummy"
  client-secret: "dummy"
  token-url: "https://id.twitch.tv/oauth2/token"